# Generated by Django 4.2.4 on 2023-08-04 11:52

import borrowing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(
                        validators=[borrowing.models.Borrowing.validate_future_date]
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        validators=[borrowing.models.Borrowing.validate_future_date]
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            borrowing.models.Borrowing.validate_actual_return_date
                        ],
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_borrowing",
                        to="book.book",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
